// Placeholder type - will be generated by Supabase CLI
// For now, we'll use a basic structure

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            users: {
                Row: {
                    id: string
                    email: string
                    full_name: string
                    role: string
                    phone: string | null
                    company: string | null
                    avatar_url: string | null
                    business_unit: string
                    is_active: boolean
                    metadata: Json
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    email: string
                    full_name: string
                    role?: string
                    phone?: string | null
                    company?: string | null
                    avatar_url?: string | null
                    business_unit?: string
                    is_active?: boolean
                    metadata?: Json
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    full_name?: string
                    role?: string
                    phone?: string | null
                    company?: string | null
                    avatar_url?: string | null
                    business_unit?: string
                    is_active?: boolean
                    metadata?: Json
                    created_at?: string
                    updated_at?: string
                }
            }
            projects: {
                Row: {
                    id: string
                    client_id: string
                    business_unit: string
                    title: string
                    description: string | null
                    project_type: string
                    status: string
                    estimated_cost: number
                    briefing: string | null
                    extracted_variables: Json
                    pricing_breakdown: Json
                    metadata: Json
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    client_id: string
                    business_unit?: string
                    title: string
                    description?: string | null
                    project_type: string
                    status: string
                    estimated_cost?: number
                    briefing?: string | null
                    extracted_variables?: Json
                    pricing_breakdown?: Json
                    metadata?: Json
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    client_id?: string
                    business_unit?: string
                    title?: string
                    description?: string | null
                    project_type?: string
                    status?: string
                    estimated_cost?: number
                    briefing?: string | null
                    extracted_variables?: Json
                    pricing_breakdown?: Json
                    metadata?: Json
                    created_at?: string
                    updated_at?: string
                }
            }
            project_renders: {
                Row: {
                    id: string
                    project_id: string
                    image_url: string
                    prompt: string
                    version: number
                    is_selected: boolean
                    status: string
                    metadata: Json
                    created_at: string
                }
                Insert: {
                    id?: string
                    project_id: string
                    image_url: string
                    prompt: string
                    version: number
                    is_selected?: boolean
                    status?: string
                    metadata?: Json
                    created_at?: string
                }
                Update: {
                    id?: string
                    project_id?: string
                    image_url?: string
                    prompt?: string
                    version?: number
                    is_selected?: boolean
                    status?: string
                    metadata?: Json
                    created_at?: string
                }
            }
            project_files: {
                Row: {
                    id: string
                    name: string
                    url: string
                    type: string
                    size: number
                    project_id: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    url: string
                    type: string
                    size: number
                    project_id: string
                    created_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    url?: string
                    type?: string
                    size?: number
                    project_id?: string
                    created_at?: string
                }
            }
            messages: {
                Row: {
                    id: string
                    content: string
                    is_ai: boolean
                    is_internal: boolean
                    user_id: string
                    project_id: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    content: string
                    is_ai?: boolean
                    is_internal?: boolean
                    user_id: string
                    project_id?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    content?: string
                    is_ai?: boolean
                    is_internal?: boolean
                    user_id?: string
                    project_id?: string | null
                    created_at?: string
                }
            }
            quotations: {
                Row: {
                    id: string
                    number: string
                    title: string
                    description: string
                    subtotal: number
                    tax: number
                    discount: number
                    total: number
                    status: string
                    valid_until: string
                    ai_generated: boolean
                    ai_confidence: number | null
                    user_id: string
                    project_id: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    number: string
                    title: string
                    description: string
                    subtotal: number
                    tax: number
                    discount?: number
                    total: number
                    status?: string
                    valid_until: string
                    ai_generated?: boolean
                    ai_confidence?: number | null
                    user_id: string
                    project_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    number?: string
                    title?: string
                    description?: string
                    subtotal?: number
                    tax?: number
                    discount?: number
                    total?: number
                    status?: string
                    valid_until?: string
                    ai_generated?: boolean
                    ai_confidence?: number | null
                    user_id?: string
                    project_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
            },
            products: {
                Row: {
                    id: string
                    name: string
                    slug: string
                    description: string
                    short_desc: string | null
                    price: number
                    compare_price: number | null
                    category: string
                    business_unit: string
                    in_stock: boolean
                    stock_quantity: number | null
                    is_rental: boolean
                    rental_price: number | null
                    images: string[]
                    features: string[]
                    ai_generated: boolean
                    show_price: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    slug: string
                    description: string
                    short_desc?: string | null
                    price: number
                    compare_price?: number | null
                    category: string
                    business_unit: string
                    in_stock?: boolean
                    stock_quantity?: number | null
                    is_rental?: boolean
                    rental_price?: number | null
                    images?: string[]
                    features?: string[]
                    ai_generated?: boolean
                    show_price?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    slug?: string
                    description?: string
                    short_desc?: string | null
                    price?: number
                    compare_price?: number | null
                    category?: string
                    business_unit?: string
                    in_stock?: boolean
                    stock_quantity?: number | null
                    is_rental?: boolean
                    rental_price?: number | null
                    images?: string[]
                    features?: string[]
                    ai_generated?: boolean
                    show_price?: boolean
                    created_at?: string
                    updated_at?: string
                }
            },
            orders: {
                Row: {
                    id: string
                    order_number: string
                    subtotal: number
                    tax: number
                    shipping: number
                    discount: number
                    total: number
                    status: string
                    payment_method: string | null
                    payment_id: string | null
                    shipping_address: string | null
                    notes: string | null
                    user_id: string
                    project_id: string | null
                    quotation_id: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    order_number: string
                    subtotal: number
                    tax: number
                    shipping?: number
                    discount?: number
                    total: number
                    status?: string
                    payment_method?: string | null
                    payment_id?: string | null
                    shipping_address?: string | null
                    notes?: string | null
                    user_id: string
                    project_id?: string | null
                    quotation_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    order_number?: string
                    subtotal?: number
                    tax?: number
                    shipping?: number
                    discount?: number
                    total?: number
                    status?: string
                    payment_method?: string | null
                    payment_id?: string | null
                    shipping_address?: string | null
                    notes?: string | null
                    user_id?: string
                    project_id?: string | null
                    quotation_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
            },
            order_items: {
                Row: {
                    id: string
                    name: string
                    quantity: number
                    unit_price: number
                    total: number
                    is_rental: boolean
                    rental_days: number | null
                    order_id: string
                    product_id: string | null
                }
                Insert: {
                    id?: string
                    name: string
                    quantity: number
                    unit_price: number
                    total: number
                    is_rental?: boolean
                    rental_days?: number | null
                    order_id: string
                    product_id?: string | null
                }
                Update: {
                    id?: string
                    name?: string
                    quantity?: number
                    unit_price?: number
                    total?: number
                    is_rental?: boolean
                    rental_days?: number | null
                    order_id?: string
                    product_id?: string | null
                }
            }
        }

        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            user_role: 'admin' | 'comercial' | 'diseno' | 'produccion' | 'marketing' | 'financiero' | 'cliente'
            business_unit: 'alma_verde' | 'alma_home'
            project_status: 'cotizacion' | 'aprobado' | 'en_diseno' | 'en_produccion' | 'instalado' | 'finalizado' | 'cancelado'
            project_type: 'stand' | 'evento' | 'branding' | 'decoracion' | 'mobiliario' | 'alquiler' | 'otro'
            payment_status: 'pendiente' | 'parcial' | 'completado' | 'reembolsado'
            invoice_status: 'borrador' | 'enviada' | 'pagada' | 'vencida' | 'cancelada'
        }
    }
}
